# Generated by Django 3.0.7 on 2020-06-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=400)),
                ('category_typr', models.CharField(max_length=400)),
                ('type_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='article_category',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='post',
            name='article_name',
            field=models.CharField(max_length=200),
        ),
    ]
