# Generated by Django 3.0.7 on 2020-06-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200630_0628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='category_id',
            new_name='categories_id',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='category_name',
            new_name='categories_name',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='category_typr',
            new_name='categories_type',
        ),
    ]
