# Generated by Django 3.0.7 on 2020-06-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200630_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categories_id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categories_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categories_type',
            new_name='category_typr',
        ),
    ]
