# Generated by Django 3.0.7 on 2020-06-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200630_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_typr',
            new_name='category_type',
        ),
    ]
